# Generated by Django 3.2.9 on 2021-11-20 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Menu', max_length=255)),
                ('displayImage', models.ImageField(default='menu/default.jpg', upload_to='menu/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menusection')),
            ],
        ),
    ]
