# Generated by Django 3.2.9 on 2021-11-21 14:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'None'), (1, 'Celery'), (2, 'Crustaceans'), (3, 'Fish'), (4, 'Milk'), (5, 'Mustard'), (6, 'Peanuts'), (7, 'Soya'), (8, 'Gluten'), (9, 'Eggs'), (10, 'Lupin'), (11, 'Molluscs'), (12, 'Nuts'), (13, 'Sesame Seeds'), (14, 'Sulphur Dioxide')], default=0, max_length=34, null=True),
        ),
    ]
