# Generated by Django 3.2.9 on 2021-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
