# Generated by Django 3.2.9 on 2021-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20211121_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='information',
            field=models.CharField(default='', help_text="Use '<br>' to start a new line or break up text.", max_length=1000),
        ),
    ]
