# Generated by Django 3.2.9 on 2021-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='information',
            field=models.CharField(default='', help_text="Use '&lt;br&gt;' to start a new line or break up text.", max_length=1000),
        ),
    ]
