# Generated by Django 3.2.9 on 2021-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
